// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4GMD2Vb4yyt_rPMV1Mp1gayUCTa9Ngg',
    appId: '1:91001722490:web:042a4fabe42c2407874dc3',
    messagingSenderId: '91001722490',
    projectId: 'chatgptrecipegenerator',
    authDomain: 'chatgptrecipegenerator.firebaseapp.com',
    storageBucket: 'chatgptrecipegenerator.appspot.com',
    measurementId: 'G-02M102PM7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkU8KM9ZuqAxIzr7gn5-FLmhYQfN-E8eg',
    appId: '1:91001722490:android:367c9dbf671208b8874dc3',
    messagingSenderId: '91001722490',
    projectId: 'chatgptrecipegenerator',
    storageBucket: 'chatgptrecipegenerator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTu5xmbKuWAo14sHXGdcwuncv4PeTvLc',
    appId: '1:91001722490:ios:4a94b9710729c8a3874dc3',
    messagingSenderId: '91001722490',
    projectId: 'chatgptrecipegenerator',
    storageBucket: 'chatgptrecipegenerator.appspot.com',
    iosBundleId: 'com.example.g14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFTu5xmbKuWAo14sHXGdcwuncv4PeTvLc',
    appId: '1:91001722490:ios:2e1cc9c5329036ef874dc3',
    messagingSenderId: '91001722490',
    projectId: 'chatgptrecipegenerator',
    storageBucket: 'chatgptrecipegenerator.appspot.com',
    iosBundleId: 'com.example.g14.RunnerTests',
  );
}
